mysql:
  image: mysql
  tag: "8.0"
  replicas: 1
  env:
    MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    MYSQL_DATABASE: "semaphore"
    MYSQL_USER: "semaphore"
    MYSQL_PASSWORD: "semaphore"
  storage:
    size: 10Gi

semaphore:
  image: semaphoreui/semaphore
  tag: "latest"
  replicas: 2
  env:
    SEMAPHORE_DB_USER: "semaphore"
    SEMAPHORE_DB_PASS: "semaphore"
    SEMAPHORE_DB_HOST: "mysql"
    SEMAPHORE_DB_PORT: "3306"
    SEMAPHORE_DB_DIALECT: "mysql"
    SEMAPHORE_DB: "semaphore"
    SEMAPHORE_ADMIN_PASSWORD: "admin"
    SEMAPHORE_ADMIN_NAME: "admin"
    SEMAPHORE_ADMIN_EMAIL: "a.j.s-engineer@outlook.com"
    SEMAPHORE_ACCESS_KEY_ENCRYPTION: "LxLP2zsSptao27pM6dTel83d5vdJOIydmktnHPrLkJU="
    ANSIBLE_HOST_KEY_CHECKING: "False"

