apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: mysql-rollout
spec:
  replicas: {{ .Values.mysql.replicas }}
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: {duration: 30s}
        - setWeight: 100
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image }}:{{ .Values.mysql.tag }}"
          env:
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "{{ .Values.mysql.env.MYSQL_RANDOM_ROOT_PASSWORD }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.mysql.env.MYSQL_DATABASE }}"
            - name: MYSQL_USER
              value: "{{ .Values.mysql.env.MYSQL_USER }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.mysql.env.MYSQL_PASSWORD }}"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql

