
apiVersion: v1
kind: Service
metadata:
  name: semaphore-service
  namespace: default  # Ensure you set the right namespace
spec:
  type: LoadBalancer  # Change to ClusterIP if using Ingress
  selector:
    app: semaphore  # Should match the label of your Semaphore deployment
  ports:
    - protocol: TCP
      port: 80         # External port exposed by the service
      targetPort: 3000  # The container's port (defined in your Rollout)

