apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/AJAFF7/Argo.git
    targetRevision: HEAD
    path: Helm2  # Update the path to the Helm chart directory
    helm:
      valueFiles:
        - values.yaml  # Specify the Helm values file
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: true




