apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: draw-rollout
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: draw-app
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause:
          duration: 30s
      - setWeight: 50
      - pause:
          duration: 60s
      - setWeight: 100
  template:
    metadata:
      labels:
        app: draw-app
    spec:
      containers:
      - name: draw-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
 #       imagePullPolicy: Always  # Ensures the latest image is always pulled
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "300Mi"  # Set memory limit to 100MB
          requests:
            memory: "200Mi"  # Optional: set a memory request to match the limit

