apiVersion: v1
kind: Service
metadata:
  name: draw-service
  namespace: default
spec:
  type: LoadBalancer # Change to ClusterIP for internal routing via Ingress
  selector:
    app: draw-app
  ports:
    - protocol: TCP
      port: 80         # External port exposed by the service
      targetPort: 8080  # The container's port (defined in your Rollout)

