apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: mongo-rollout
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mongo-app
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause:
          duration: 30s
      - setWeight: 50
      - pause:
          duration: 60s
      - setWeight: 100
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
      - name: mongo-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always  # Ensures the latest image is always pulled
        ports:
        - containerPort: 27017
        resources:
          limits:
            memory: "500Mi"  # Set memory limit to 100MB
          requests:
            memory: "500Mi"  # Optional: set a memory request to match the limit
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "jaff"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "mdb5550140"
        volumeMounts:
          - name: mongo-data
            mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc



