apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: default
spec:
  selector:
    app: mongo-app
  ports:
    - port: 27017
      targetPort: 27017
  type: LoadBalancer  # Expose the service externally as a LoadBalancer
